services:
  postgres:
    container_name: postgres_fynd_core_api
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=usr_fynd_core
      - POSTGRES_PASSWORD=fynd_core
      - POSTGRES_DB=fynd
  qdrant:
    container_name: qdrant_fynd_core_api
    image: qdrant/qdrant:v1.9.0
    ports:
      - "6333:6333"
    volumes:
      - qdrant:/qdrant/storage

volumes:
  database:
  qdrant: